exports.cityStateMapping = new Map([
    ["ALWAR", "JAIPUR"],
    ["BHARATPUR", "JAIPUR"],
    ["CHURU", "JAIPUR"],
    ["DHOLPUR", "JAIPUR"],
    ["HNUMANGARH", "JAIPUR"],
    ["JAIPUR", "JAIPUR"],
    ["JHUNJHUNU", "JAIPUR"],
    ["KARAULI", "JAIPUR"],
    ["SIKAR", "JAIPUR"],
    ["SRI GANGANAGAR", "JAIPUR"],
    ["TONK", "JAIPUR"],
    ["MGH JAIPUR", "JAIPUR"],
    ["JNU JAIPUR", "JAIPUR"],
    ["NIMS JAIPUR", "JAIPUR"],

    ["AJMER", "JODHPUR"],
    ["BARMER", "JODHPUR"],
    ["BIKANER", "JODHPUR"],
    ["PALI", "JODHPUR"],
    ["JALORE", "JODHPUR"],
    ["JODHPUR", "JODHPUR"],
    ["NAGAUR", "JODHPUR"],
    ["SIROHI", "JODHPUR"],

    ["BHILWARA", "UDAIPUR"],
    ["BANSWARA", "UDAIPUR"],
    ["CHHITORGARH", "UDAIPUR"],
    ["DUNGARPUR", "UDAIPUR"],
    ["SAGWARA DUNGARPUR", "UDAIPUR"],
    ["JHALAWAR", "UDAIPUR"],
    ["KOTA", "UDAIPUR"],
    ["RAJSAMAND", "UDAIPUR"],
    ["UDAIPUR", "UDAIPUR"],
    ["PIMS UDAIPUR", "UDAIPUR"],
    ["GMCG UDAIPUR", "UDAIPUR"],
    ["AIIMS UDAIPUR", "UDAIPUR"],
    ["AIMS RAJSAMAND", "UDAIPUR"],

    ["Coronation Hospital, Dehradun ", "IGMC HP"],
    ["Haldwani", "IGMC HP"],
    ["Pithoragrh", "IGMC HP"],
    ["AIIMS Rishikesh,", "IGMC HP"],
    ["Mahant Indresh Hospital,Dehradun", "IGMC HP"],
    ["Roorkee", "IGMC HP"],
    ["Himalayan Institute Hospital,Dehradun", "IGMC HP"],
    
    ["BHOPAL", "MGM INDORE"],
    ["BARWANI", "MGM INDORE"],
    ["BALAGHAT", "MGM INDORE"],
    ["BURHANPUR", "MGM INDORE"],
    ["DEWAS", "MGM INDORE"],
    ["DHAR", "MGM INDORE"],
    ["GWALIOR", "MGM INDORE"],
    ["INDORE", "MGM INDORE"],
    ["JABALPUR", "MGM INDORE"],
    ["KHANDWA", "MGM INDORE"],
    ["KHARGONE", "MGM INDORE"],
    ["NEEMUCH", "MGM INDORE"],
    ["RATLAM", "MGM INDORE"],
    ["REWA", "MGM INDORE"],
    ["SAGAR", "MGM INDORE"],
    ["SEONI", "MGM INDORE"],
    ["SHIVPURI", "MGM INDORE"],
    ["UJJAIN", "MGM INDORE"],
    ["MORENA", "MGM INDORE"],
    ["SIDHI", "MGM INDORE"],
    ["SHAHDOL", "MGM INDORE"],
    ["CHHINDWARA", "MGM INDORE"],

    ["BALAGHAT", "PJLN RAIPUR"],
    ["JABALPUR", "PJLN RAIPUR"],
    ["SEONI", "PJLN RAIPUR"],

    ["DURG", "PJLN RAIPUR"],
    ["BILASPUR", "PJLN RAIPUR"],
    ["SARGUJA", "PJLN RAIPUR"],
    ["BASTAR", "PJLN RAIPUR"],
    ["KORBA", "PJLN RAIPUR"],
    ["RAIGARH", "PJLN RAIPUR"],
    ["RAJNANDGAON", "PJLN RAIPUR"],
    

    // Add more city-state mappings as needed
  ]);
