const Chhatisgarh  = [
    {value: "RAIPUR", label: "RAIPUR"},
    {value: "DURG", label: "DURG"},
    {value: "BILASPUR", label: "BILASPUR"},
    {value: "SARGUJA", label: "SARGUJA"},
    {value: "BASTAR", label: "BASTAR"},
    {value: "KORBA", label: "KORBA"},
    {value: "RAIGARH", label: "RAIGARH"},
    {value: "RAJNANDGAON", label: "RAJNANDGAON"},
    
]
const MadhyaPradesh  = [
    {value: "BHOPAL", label: "BHOPAL"},
    {value: "BARWANI", label: "BARWANI"},
    {value: "BALAGHAT", label: "BALAGHAT"},
    {value: "BURHANPUR", label: "BURHANPUR"},
    {value: "DEWAS", label: "DEWAS"},
    {value: "DHAR", label: "DHAR"},
    {value: "GWALIOR", label: "GWALIOR"},
    {value: "INDORE", label: "INDORE"},
    {value: "JABALPUR", label: "JABALPUR"},
    {value: "KHANDWA", label: "KHANDWA"},
    {value: "MANDSOUR", label: "MANDSOUR"},
    {value: "KHARGONE", label: "KHARGONE"},
    {value: "NEEMUCH", label: "NEEMUCH"},
    {value: "RATLAM", label: "RATLAM"},
    {value: "REWA", label: "REWA"},
    {value: "SAGAR", label: "SAGAR"},
    {value: "SEONI", label: "SEONI"},
    {value: "SHIVPURI", label: "SHIVPURI"},
    {value: "UJJAIN", label: "UJJAIN"},
    {value: "BALAGHAT to RPR", label: "BALAGHAT to RPR"},
    {value: "JABALPUR to RPR", label: "JABALPUR to RPR"},
    {value: "SEONI to RPR", label: "SEONI to RPR"},
    {value: "MORENA", label: "MORENA"},
    {value: "CHHINDWARA", label: "CHHINDWARA"},
    {value: "SIDHI", label: "SIDHI"},
    {value: "SHAHDOL", label: "SHAHDOL"},
    {value: "SATNA", label: "SATNA"},
    {value: "BETUL", label: "BETUL"},
    
]

const Uttrakhand  = [
    {value: "dehradun", label: "dehradun"},
    {value: "haldwani", label: "haldwani"},
    {value: "rishikesh", label: "rishikesh"},
    {value: "roorkee", label: "roorkee"},
    {value: "pithoragarh", label: "pithoragarh"},    
]

const Rajasthan  = [
    {value: "UDAIPUR", label: "UDAIPUR"},
    {value: "PIMS UDAIPUR", label: "PIMS UDAIPUR"},
    {value: "GMCG UDAIPUR", label: "GMCG UDAIPUR"},
    {value: "AIIMS UDAIPUR", label: "AIIMS UDAIPUR"},
    {value: "AIMS RAJSAMAND", label: "AIMS RAJSAMAND"},  
    {value: "ALWAR", label: "ALWAR"},
    {value: "BHARATPUR", label: "BHARATPUR"},
    {value: "CHURU", label: "CHURU"},
    {value: "DHOLPUR", label: "DHOLPUR"},
    {value: "HNUMANGARH", label: "HNUMANGARH"},
    {value: "JAIPUR", label: "JAIPUR"},
    {value: "JHUNJHUNU", label: "JHUNJHUNU"},
    {value: "KARAULI", label: "KARAULI"},
    {value: "SIKAR", label: "SIKAR"},
    {value: "SRI GANGANAGAR", label: "SRI GANGANAGAR"},
    {value: "TONK", label: "TONK"},
    {value: "JNU JAIPUR", label: "JNU JAIPUR"},
    {value: "NIMS JAIPUR", label: "NIMS JAIPUR"},
    {value: "AJMER", label: "AJMER"},
    {value: "BARMER", label: "BARMER"},
    {value: "BIKANER", label: "BIKANER"},
    {value: "PALI", label: "PALI"},
    {value: "JALORE", label: "JALORE"},
    {value: "JODHPUR", label: "JODHPUR"},
    {value: "NAGAUR", label: "NAGAUR"},
    {value: "SIROHI", label: "SIROHI"},
    {value: "BHILWARA", label: "BHILWARA"},
    {value: "BANSWARA", label: "BANSWARA"},
    {value: "CHITTORGARH", label: "CHITTORGARH"},
    {value: "SAGWARA DUNGARPUR", label: "SAGWARA DUNGARPUR"},
    {value: "JHALAWAR", label: "JHALAWAR"},
    {value: "KOTA", label: "KOTA"},
    {value: "RAJSAMAND", label: "RAJSAMAND"},
    {value: "DUNGARPUR", label: "DUNGARPUR"},
    {value: "MGH JAIPUR", label: "MGH JAIPUR"},

]

module.exports = { MadhyaPradesh , Uttrakhand, Rajasthan , Chhatisgarh}