exports.citys = [
    { value: "RAIPUR", label: "RAIPUR" },
    { value: "DURG", label: "DURG" },
    { value: "BILASPUR", label: "BILASPUR" },
    { value: "SARGUJA ", label: "SARGUJA " },
    { value: "BASTAR", label: "BASTAR" },
    { value: "KORBA", label: "KORBA" },
    { value: "RAIGARH", label: "RAIGARH" },
    { value: "RAJNANDGAON", label: "RAJNANDGAON" },
    { value: "BHOPAL", label: "BHOPAL" },
    { value: "BARWANI", label: "BARWANI" },
    { value: "BALAGHAT", label: "BALAGHAT" },
    { value: "BURHANPUR", label: "BURHANPUR" },
    { value: "DEWAS", label: "DEWAS" },
    { value: "DHAR", label: "DHAR" },
    { value: "GWALIOR", label: "GWALIOR" },
    { value: "INDORE", label: "INDORE" },
    { value: "JABALPUR", label: "JABALPUR" },
    { value: "KHANDWA", label: "KHANDWA" },
    { value: "KHARGONE", label: "KHARGONE" },
    { value: "MANDSOUR", label: "MANDSOUR" },
    { value: "NEEMUCH", label: "NEEMUCH" },
    { value: "RATLAM", label: "RATLAM" },
    { value: "REWA", label: "REWA" },
    { value: "SAGAR", label: "SAGAR" },
    { value: "SEONI", label: "SEONI" },
    { value: "UJJAIN", label: "UJJAIN" },
    { value: "BALAGHAT ", label: "BALAGHAT " },
    { value: "SHIVPURI", label: "SHIVPURI" },
    { value: "SIDHI", label: "SIDHI" },
    { value: "MORENA", label: "MORENA" },
    { value: "SHAHDOL", label: "SHAHDOL" },
    { value: "CHHINDWARA", label: "CHHINDWARA" },
    { value: "CHD", label: "Coronation Hospital, Dehradun " },
    { value: "Haldwani", label: "Haldwani" },
    { value: "Pithoragrh", label: "Pithoragrh" },
    { value: "AIIMS Rishikesh, ", label: "AIIMS Rishikesh, " },
    { value: "MIHD", label: "Mahant Indresh Hospital,Dehradun" },
    { value: "Roorkee", label: "Roorkee" },
    { value: "HIHD", label: "Himalayan Institute Hospital,Dehradun" },
    { value: "ALWAR", label: "ALWAR" },
    { value: "BHARATPUR", label: "BHARATPUR" },
    { value: "CHURU", label: "CHURU" },
    { value: "DHOLPUR ", label: "SARGUJA " },
    { value: "HNUMANGARH", label: "HNUMANGARH" },
    { value: "JAIPUR", label: "JAIPUR" },
    { value: "JHUNJHUNU", label: "JHUNJHUNU" },
    { value: "KARAULI", label: "KARAULI" },
 { value: "SIKAR", label: "SIKAR" },
 { value: "SRI GANGANAGAR", label: "SRI GANGANAGAR" },
 { value: "TONK", label: "TONK" },
 { value: "MGH JAIPUR", label: "MGH JAIPUR" },
 { value: "JNU JAIPUR", label: "JNU JAIPUR" },
 { value: "NIMS JAIPUR", label: "NIMS JAIPUR" },
 { value: "AJMER", label: "AJMER" },
 { value: "BARMER", label: "BARMER" },
 { value: "BIKANER", label: "BIKANER" },
 { value: "PALI", label: "PALI" },
 { value: "JALORE", label: "JALORE" },
 { value: "JODHPUR", label: "JODHPUR" },
 { value: "NAGAUR", label: "NAGAUR" },
 { value: "SIROHI", label: "SIROHI" },
 { value: "KARAULI", label: "KARAULI" },
{ value: "BHILWARA", label: "BHILWARA" },
{ value: "BANSWARA", label: "BANSWARA" },
{ value: "CHHITORGARH", label: "CHHITORGARH" },
{ value: "DUNGARPUR", label: "DUNGARPUR" },
{ value: "SAGWARA DUNGARPUR", label: "SAGWARA DUNGARPUR" },
{ value: "JHALAWAR", label: "JHALAWAR" },
{ value: "KOTA", label: "KOTA" },
{ value: "RAJSAMAND", label: "RAJSAMAND" },
{ value: "UDAIPUR", label: "UDAIPUR" },
{ value: "PIMS UDAIPUR", label: "PIMS UDAIPUR" },
{ value: "GMCG UDAIPUR", label: "GMCG UDAIPUR" },
{ value: "AIIMS UDAIPUR", label: "AIIMS UDAIPUR" },
{ value: "AIMS RAJSAMAND", label: "AIMS RAJSAMAND" },
]