exports.MpState = [
    { value: "BHOPAL", label: "BHOPAL" },
    { value: "BARWANI", label: "BARWANI" },
    { value: "BALAGHAT", label: "BALAGHAT" },
    { value: "BURHANPUR", label: "BURHANPUR" },
    { value: "DEWAS", label: "DEWAS" },
    { value: "DHAR", label: "DHAR" },
    { value: "GWALIOR", label: "GWALIOR" },
    { value: "INDORE", label: "INDORE" },
    { value: "JABALPUR", label: "JABALPUR" },
    { value: "KHANDWA", label: "KHANDWA" },
    { value: "KHARGONE", label: "KHARGONE" },
    { value: "MANDSOUR", label: "MANDSOUR" },
    { value: "NEEMUCH", label: "NEEMUCH" },
    { value: "RATLAM", label: "RATLAM" },
    { value: "REWA", label: "REWA" },
    { value: "SAGAR", label: "SAGAR" },
    { value: "SEONI", label: "SEONI" },
    { value: "UJJAIN", label: "UJJAIN" },
    { value: "BALAGHAT ", label: "BALAGHAT " },
    { value: "SHIVPURI", label: "SHIVPURI" },
    { value: "SIDHI", label: "SIDHI" },
    { value: "MORENA", label: "MORENA" },
    { value: "SHAHDOL", label: "SHAHDOL" },
    { value: "CHHINDWARA", label: "CHHINDWARA" },
]