exports.RJState = [
    { value: "ALWAR", label: "ALWAR" },
    { value: "BHARATPUR", label: "BHARATPUR" },
    { value: "CHURU", label: "CHURU" },
    { value: "DHOLPUR ", label: "SARGUJA " },
    { value: "HNUMANGARH", label: "HNUMANGARH" },
    { value: "JAIPUR", label: "JAIPUR" },
    { value: "JHUNJHUNU", label: "JHUNJHUNU" },
    { value: "KARAULI", label: "KARAULI" },
 { value: "SIKAR", label: "SIKAR" },
 { value: "SRI GANGANAGAR", label: "SRI GANGANAGAR" },
 { value: "TONK", label: "TONK" },
 { value: "MGH JAIPUR", label: "MGH JAIPUR" },
 { value: "JNU JAIPUR", label: "JNU JAIPUR" },
 { value: "NIMS JAIPUR", label: "NIMS JAIPUR" },
 { value: "AJMER", label: "AJMER" },
 { value: "BARMER", label: "BARMER" },
 { value: "BIKANER", label: "BIKANER" },
 { value: "PALI", label: "PALI" },
 { value: "JALORE", label: "JALORE" },
 { value: "JODHPUR", label: "JODHPUR" },
 { value: "NAGAUR", label: "NAGAUR" },
 { value: "SIROHI", label: "SIROHI" },
 { value: "KARAULI", label: "KARAULI" },
{ value: "BHILWARA", label: "BHILWARA" },
{ value: "BANSWARA", label: "BANSWARA" },
{ value: "CHHITORGARH", label: "CHHITORGARH" },
{ value: "DUNGARPUR", label: "DUNGARPUR" },
{ value: "SAGWARA DUNGARPUR", label: "SAGWARA DUNGARPUR" },
{ value: "JHALAWAR", label: "JHALAWAR" },
{ value: "KOTA", label: "KOTA" },
{ value: "RAJSAMAND", label: "RAJSAMAND" },
{ value: "UDAIPUR", label: "UDAIPUR" },
{ value: "PIMS UDAIPUR", label: "PIMS UDAIPUR" },
{ value: "GMCG UDAIPUR", label: "GMCG UDAIPUR" },
{ value: "AIIMS UDAIPUR", label: "AIIMS UDAIPUR" },
{ value: "AIMS RAJSAMAND", label: "AIMS RAJSAMAND" },
]