
exports.states = [
  // { value: "AN", label: "Andaman and Nicobar Islands" },
  // { value: "Andhra Pradesh", label: "Andhra Pradesh" },
  // { value: "Arunachal Pradesh", label: "Arunachal Pradesh" },
  // { value: "Assam", label: "Assam" },
  // { value: "Bihar", label: "Bihar" },
  { value: "Chhattisgarh", label: "Chhattisgarh" },
  // { value: "Chandigarh", label: "Chandigarh" },
  // { value: "DN", label: "Dadra and Nagar Haveli and Daman and Diu" },
  // { value: "Delhi", label: "Delhi" },
  // { value: "Goa", label: "Goa" },
  // { value: "Gujarat", label: "Gujarat" },
  // { value: "Haryana", label: "Haryana" },
  // { value: "Himachal Pradesh", label: "Himachal Pradesh" },
  // { value: "JK", label: "Jammu and Kashmir" },
  // { value: "Jharkhand", label: "Jharkhand" },
  // { value: "Karnataka", label: "Karnataka" },
  // { value: "Kerala", label: "Kerala" },
  // { value: "Lakshadweep", label: "Lakshadweep" },
  { value: "Madhya Pradesh", label: "Madhya Pradesh" },
  // { value: "Maharashtra", label: "Maharashtra" },
  // { value: "Manipur", label: "Manipur" },
  // { value: "Meghalaya", label: "Meghalaya" },
  // { value: "MZ", label: "Mizoram" },
  // { value: "NL", label: "Nagaland" },
  // { value: "OR", label: "Odisha" },
  // { value: "PY", label: "Puducherry" },
  // { value: "Punjab", label: "Punjab" },
  { value: "Rajasthan", label: "Rajasthan" },
  // { value: "SK", label: "Sikkim" },
  // { value: "TN", label: "Tamil Nadu" },
  // { value: "Telangana", label: "Telangana" },
  // { value: "TR", label: "Tripura" },
  // { value: "Uttar Pradesh", label: "Uttar Pradesh" },
  { value: "Uttarakhand", label: "Uttarakhand" },
  // { value: "WB", label: "West Bengal" },
];


